/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GUI_Board_CheckListener */

#ifndef _Included_GUI_Board_CheckListener
#define _Included_GUI_Board_CheckListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GUI_Board_CheckListener
 * Method:    isValidPieceToSelect
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_GUI_Board_00024CheckListener_isValidPieceToSelect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GUI_Board_CheckListener
 * Method:    isValidMove
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_GUI_Board_00024CheckListener_isValidMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GUI_Board_CheckListener
 * Method:    placingPieces
 * Signature: ()[[C
 */
JNIEXPORT jobjectArray JNICALL Java_GUI_Board_00024CheckListener_placingPieces
  (JNIEnv *, jclass);

/*
 * Class:     GUI_Board_CheckListener
 * Method:    move
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_GUI_Board_00024CheckListener_move
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     GUI_Board_CheckListener
 * Method:    predictedMoves
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_GUI_Board_00024CheckListener_predictedMoves
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
