/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Board */

#ifndef _Included_main_Board
#define _Included_main_Board
#ifdef __cplusplus
extern "C" {
#endif
#undef main_Board_FOCUS_TRAVERSABLE_UNKNOWN
#define main_Board_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef main_Board_FOCUS_TRAVERSABLE_DEFAULT
#define main_Board_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef main_Board_FOCUS_TRAVERSABLE_SET
#define main_Board_FOCUS_TRAVERSABLE_SET 2L
#undef main_Board_TOP_ALIGNMENT
#define main_Board_TOP_ALIGNMENT 0.0f
#undef main_Board_CENTER_ALIGNMENT
#define main_Board_CENTER_ALIGNMENT 0.5f
#undef main_Board_BOTTOM_ALIGNMENT
#define main_Board_BOTTOM_ALIGNMENT 1.0f
#undef main_Board_LEFT_ALIGNMENT
#define main_Board_LEFT_ALIGNMENT 0.0f
#undef main_Board_RIGHT_ALIGNMENT
#define main_Board_RIGHT_ALIGNMENT 1.0f
#undef main_Board_serialVersionUID
#define main_Board_serialVersionUID -7644114512714619750LL
#undef main_Board_serialVersionUID
#define main_Board_serialVersionUID 4613797578919906343LL
#undef main_Board_INCLUDE_SELF
#define main_Board_INCLUDE_SELF 1L
#undef main_Board_SEARCH_HEAVYWEIGHTS
#define main_Board_SEARCH_HEAVYWEIGHTS 1L
#undef main_Board_OPENED
#define main_Board_OPENED 1L
#undef main_Board_serialVersionUID
#define main_Board_serialVersionUID 4497834738069338734LL
#undef main_Board_DEFAULT_CURSOR
#define main_Board_DEFAULT_CURSOR 0L
#undef main_Board_CROSSHAIR_CURSOR
#define main_Board_CROSSHAIR_CURSOR 1L
#undef main_Board_TEXT_CURSOR
#define main_Board_TEXT_CURSOR 2L
#undef main_Board_WAIT_CURSOR
#define main_Board_WAIT_CURSOR 3L
#undef main_Board_SW_RESIZE_CURSOR
#define main_Board_SW_RESIZE_CURSOR 4L
#undef main_Board_SE_RESIZE_CURSOR
#define main_Board_SE_RESIZE_CURSOR 5L
#undef main_Board_NW_RESIZE_CURSOR
#define main_Board_NW_RESIZE_CURSOR 6L
#undef main_Board_NE_RESIZE_CURSOR
#define main_Board_NE_RESIZE_CURSOR 7L
#undef main_Board_N_RESIZE_CURSOR
#define main_Board_N_RESIZE_CURSOR 8L
#undef main_Board_S_RESIZE_CURSOR
#define main_Board_S_RESIZE_CURSOR 9L
#undef main_Board_W_RESIZE_CURSOR
#define main_Board_W_RESIZE_CURSOR 10L
#undef main_Board_E_RESIZE_CURSOR
#define main_Board_E_RESIZE_CURSOR 11L
#undef main_Board_HAND_CURSOR
#define main_Board_HAND_CURSOR 12L
#undef main_Board_MOVE_CURSOR
#define main_Board_MOVE_CURSOR 13L
#undef main_Board_NORMAL
#define main_Board_NORMAL 0L
#undef main_Board_ICONIFIED
#define main_Board_ICONIFIED 1L
#undef main_Board_MAXIMIZED_HORIZ
#define main_Board_MAXIMIZED_HORIZ 2L
#undef main_Board_MAXIMIZED_VERT
#define main_Board_MAXIMIZED_VERT 4L
#undef main_Board_MAXIMIZED_BOTH
#define main_Board_MAXIMIZED_BOTH 6L
#undef main_Board_serialVersionUID
#define main_Board_serialVersionUID 2673458971256075116LL
/*
 * Class:     main_Board
 * Method:    isValidPieceToSelect
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_main_Board_isValidPieceToSelect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_Board
 * Method:    placingPieces
 * Signature: ()[[C
 */
JNIEXPORT jobjectArray JNICALL Java_main_Board_placingPieces
  (JNIEnv *, jclass);

/*
 * Class:     main_Board
 * Method:    move
 * Signature: (IIIIZ)V
 */
JNIEXPORT void JNICALL Java_main_Board_move
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean);

/*
 * Class:     main_Board
 * Method:    removeCaptured
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_main_Board_removeCaptured
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_Board
 * Method:    predictedMoves
 * Signature: (II)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_main_Board_predictedMoves
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_Board
 * Method:    captureRule
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_main_Board_captureRule
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_Board
 * Method:    restart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Board_restart
  (JNIEnv *, jclass);

/*
 * Class:     main_Board
 * Method:    displaying
 * Signature: ()[[C
 */
JNIEXPORT jobjectArray JNICALL Java_main_Board_displaying
  (JNIEnv *, jobject);

/*
 * Class:     main_Board
 * Method:    getTurn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_Board_getTurn
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
